# Generated by Django 4.1.1 on 2022-10-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangopostgis', '0004_indstates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indstates',
            name='nl_name_2',
        ),
        migrations.RemoveField(
            model_name='indstates',
            name='varname_2',
        ),
    ]
