# Generated by Django 4.1.1 on 2022-11-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangopostgis', '0006_india'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='india',
            name='contains',
        ),
        migrations.RemoveField(
            model_name='india',
            name='name_nonla',
        ),
        migrations.RemoveField(
            model_name='india',
            name='name_obsol',
        ),
        migrations.RemoveField(
            model_name='india',
            name='waspartof',
        ),
        migrations.RemoveField(
            model_name='india',
            name='wbother',
        ),
        migrations.RemoveField(
            model_name='india',
            name='www',
        ),
    ]
