# Generated by Django 4.1.1 on 2022-11-03 11:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopostgis', '0007_remove_india_contains_remove_india_name_nonla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indblocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_0', models.BigIntegerField()),
                ('iso', models.CharField(max_length=3)),
                ('name_0', models.CharField(max_length=75)),
                ('id_1', models.BigIntegerField()),
                ('name_1', models.CharField(max_length=75)),
                ('id_2', models.BigIntegerField()),
                ('name_2', models.CharField(max_length=75)),
                ('id_3', models.BigIntegerField()),
                ('name_3', models.CharField(max_length=75)),
                ('type_3', models.CharField(max_length=50)),
                ('engtype_3', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
